spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/device_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.example.devicememory: INFO

server:
  port: 8080
